#!/bin/bash
set -e

DATA_DIR="${OPENHOST_APP_DATA_DIR:-/app/data}"
PG_DATA="/var/lib/postgresql/data"
MINIO_DATA="$DATA_DIR/minio"
MINIO_BUCKET="plane-uploads"

# Persist secret keys in the data directory so they survive restarts
SECRET_KEYS_FILE="$DATA_DIR/.secret_keys"
if [ -f "$SECRET_KEYS_FILE" ]; then
    source "$SECRET_KEYS_FILE"
fi
if [ -z "$SECRET_KEY" ]; then
    SECRET_KEY=$(uuidgen | tr -d '-')
fi
if [ -z "$LIVE_SERVER_SECRET_KEY" ]; then
    LIVE_SERVER_SECRET_KEY=$(uuidgen | tr -d '-')
fi
# Save for next boot
cat > "$SECRET_KEYS_FILE" << EOF
SECRET_KEY=$SECRET_KEY
LIVE_SERVER_SECRET_KEY=$LIVE_SERVER_SECRET_KEY
EOF

# --- Initialize PostgreSQL ---
# PG_DATA is container-local (not on the bind mount) so postgres can
# chmod/chown freely. This avoids permission failures under rootless
# podman with idmapped mounts. Data survives restarts via pg_dump
# backups on the persistent mount (see pg-backup in supervisor.conf).
mkdir -p "$PG_DATA"
chown postgres:postgres "$PG_DATA"

if [ ! -f "$PG_DATA/PG_VERSION" ]; then
    echo "Initializing PostgreSQL database..."
    su postgres -c "initdb -D $PG_DATA --encoding=UTF8 --locale=C"
    echo "host all all 127.0.0.1/32 trust" >> "$PG_DATA/pg_hba.conf"
    echo "local all all trust" >> "$PG_DATA/pg_hba.conf"

    su postgres -c "pg_ctl -D $PG_DATA -l /tmp/pg_init.log start -w"
    su postgres -c "createdb plane"

    # Restore from backup if one exists on the persistent mount
    if [ -f "$DATA_DIR/plane.sql.gz" ]; then
        echo "Restoring database from backup..."
        gunzip -c "$DATA_DIR/plane.sql.gz" | su postgres -c "psql -q plane" 2>/dev/null || true
        echo "Database restored."
    fi

    su postgres -c "pg_ctl -D $PG_DATA stop -w"
    echo "PostgreSQL initialized."
else
    echo "PostgreSQL data directory already exists, skipping init."
fi

# --- Ensure data directories exist ---
mkdir -p "$DATA_DIR/redis" "$DATA_DIR/rabbitmq" "$DATA_DIR/minio"

# --- Ensure MinIO bucket directory exists ---
mkdir -p "$MINIO_DATA/$MINIO_BUCKET"

# --- Derive domain from environment ---
# OPENHOST_ZONE_DOMAIN is set by the router (e.g. "zack.host.imbue.com")
# OPENHOST_APP_NAME is set by the router (e.g. "plane2")
# The app is accessed at {app_name}.{zone_domain} via subdomain routing
if [ -n "$OPENHOST_ZONE_DOMAIN" ]; then
    APP_SUBDOMAIN="${OPENHOST_APP_NAME:-plane}"
    DOMAIN_NAME="${DOMAIN_NAME:-${APP_SUBDOMAIN}.${OPENHOST_ZONE_DOMAIN}}"
else
    DOMAIN_NAME="${DOMAIN_NAME:-localhost}"
fi

# Protocol: use https when behind the OpenHost router (which handles TLS)
if [ -n "$OPENHOST_ZONE_DOMAIN" ]; then
    APP_PROTOCOL="${APP_PROTOCOL:-https}"
else
    APP_PROTOCOL="${APP_PROTOCOL:-http}"
fi
WEB_URL="${APP_PROTOCOL}://${DOMAIN_NAME}"

# --- Write plane.env ---
cat > /app/plane.env << ENVEOF
# Auto-generated by start.sh
APP_DOMAIN=${DOMAIN_NAME}
APP_RELEASE=stable

# Database (local PostgreSQL)
DATABASE_URL=postgresql://postgres@127.0.0.1:5432/plane

# Redis (local)
REDIS_URL=redis://127.0.0.1:6379/

# RabbitMQ (local, default guest creds)
AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

# Web URLs
WEB_URL=${WEB_URL}
CORS_ALLOWED_ORIGINS=${WEB_URL},http://127.0.0.1:3004

# MinIO (local S3-compatible storage)
USE_MINIO=1
AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=plane
AWS_SECRET_ACCESS_KEY=planeminio
AWS_S3_ENDPOINT_URL=http://127.0.0.1:9000
AWS_S3_BUCKET_NAME=${MINIO_BUCKET}

# Security
SECRET_KEY=${SECRET_KEY}
LIVE_SERVER_SECRET_KEY=${LIVE_SERVER_SECRET_KEY}

# Server
SITE_ADDRESS=:8080
FILE_SIZE_LIMIT=5242880
GUNICORN_WORKERS=1
API_RATE_LIMIT=60/minute
ENVEOF

echo "Environment configured."

# Export all env vars for supervisor child processes
set -a
source /app/plane.env
export DATA_DIR
set +a

# --- Squash migrations for faster first boot ---
cd /app/backend && python /app/squash_migrations.py

# --- Launch all services via supervisor ---
exec supervisord -c /app/supervisor.conf
