#!/bin/bash
set -e

PG_DATA="/app/data/postgres"
MINIO_DATA="/app/data/minio"
MINIO_BUCKET="plane-uploads"

# Generate a secret key if not already set
if [ -z "$SECRET_KEY" ]; then
    SECRET_KEY=$(uuidgen | tr -d '-')
fi
if [ -z "$LIVE_SERVER_SECRET_KEY" ]; then
    LIVE_SERVER_SECRET_KEY=$(uuidgen | tr -d '-')
fi

# --- Initialize PostgreSQL if needed ---
if [ ! -f "$PG_DATA/PG_VERSION" ]; then
    echo "Initializing PostgreSQL database..."
    su postgres -c "initdb -D $PG_DATA --encoding=UTF8 --locale=C"
    # Allow local connections without password
    echo "host all all 127.0.0.1/32 trust" >> "$PG_DATA/pg_hba.conf"
    echo "local all all trust" >> "$PG_DATA/pg_hba.conf"

    # Start postgres temporarily to create the database
    su postgres -c "pg_ctl -D $PG_DATA -l /tmp/pg_init.log start -w"
    su postgres -c "createdb plane"
    su postgres -c "pg_ctl -D $PG_DATA stop -w"
    echo "PostgreSQL initialized."
fi

# --- Ensure MinIO bucket directory exists ---
mkdir -p "$MINIO_DATA/$MINIO_BUCKET"

# --- Derive domain from environment ---
# OPENHOST_ZONE_DOMAIN is set by the router (e.g. "zack.host.imbue.com")
# Plane is accessed at plane.{zone_domain} via subdomain routing
if [ -n "$OPENHOST_ZONE_DOMAIN" ]; then
    DOMAIN_NAME="${DOMAIN_NAME:-plane.${OPENHOST_ZONE_DOMAIN}}"
else
    DOMAIN_NAME="${DOMAIN_NAME:-localhost}"
fi

# Protocol: the router handles TLS, so internal is http
APP_PROTOCOL="${APP_PROTOCOL:-http}"
WEB_URL="${APP_PROTOCOL}://${DOMAIN_NAME}"

# --- Write plane.env ---
cat > /app/plane.env << ENVEOF
# Auto-generated by start.sh
APP_DOMAIN=${DOMAIN_NAME}
APP_RELEASE=stable

# Database (local PostgreSQL)
DATABASE_URL=postgresql://postgres@127.0.0.1:5432/plane

# Redis (local)
REDIS_URL=redis://127.0.0.1:6379/

# RabbitMQ (local, default guest creds)
AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

# Web URLs
WEB_URL=${WEB_URL}
CORS_ALLOWED_ORIGINS=${WEB_URL}

# MinIO (local S3-compatible storage)
USE_MINIO=1
AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=plane
AWS_SECRET_ACCESS_KEY=planeminio
AWS_S3_ENDPOINT_URL=http://127.0.0.1:9000
AWS_S3_BUCKET_NAME=${MINIO_BUCKET}

# Security
SECRET_KEY=${SECRET_KEY}
LIVE_SERVER_SECRET_KEY=${LIVE_SERVER_SECRET_KEY}

# Server
SITE_ADDRESS=:8080
FILE_SIZE_LIMIT=5242880
GUNICORN_WORKERS=1
API_RATE_LIMIT=60/minute
ENVEOF

echo "Environment configured."

# Export all env vars for supervisor child processes
set -a
source /app/plane.env
set +a

# --- Launch all services via supervisor ---
exec supervisord -c /app/supervisor.conf
